server:
  port: 9192
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_app?createDatabaseIfNotExist=true
    username: postgres
    password: System
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: create-drop

    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        format_sql: true
    database: postgresql
  application:
    name: user
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9192/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

logging:
  level:
    org:
      hibernate:
        type: trace

